apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "graph.fullname" . }}"
  labels:
    {{- include "graph.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{{ include "graph.name" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "graph.name" . }}"
    spec:
      containers:
        - name: graph
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"