apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graph-hpa
  namespace: adriel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graph-deployment  # Nome do deployment da sua aplicação
  minReplicas: 1  # Número mínimo de pods
  maxReplicas: 5  # Número máximo de pods
  metrics:
    - type: Resource
      resource:
        name: cpu  # Escala com base na utilização de CPU
        target:
          type: Utilization
          averageUtilization: 3000  # Quando a utilização de CPU atingir 80%, escalar