apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graph
  namespace: adriel
spec:
  rules:
    - host: graph.lab.havan.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: graph
                port:
                  number: 3000
